"""Add picture_url to Ghosts model

Revision ID: abc31550f99e
Revises: f32d98284349
Create Date: 2024-10-29 20:02:21.352412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc31550f99e'
down_revision = 'f32d98284349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ghostbusters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ghostbusters', schema=None) as batch_op:
        batch_op.drop_column('picture_url')

    # ### end Alembic commands ###
