"""ghosts table

Revision ID: f32d98284349
Revises: 
Create Date: 2024-10-29 16:15:22.943489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f32d98284349'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ghostbusters',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('user_role', sa.Enum('ADMIN', 'GHOSTBUSTER', name='userrole'), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_ghostbusters_email'), 'ghostbusters', ['email'], unique=True)
    op.create_index(op.f('ix_ghostbusters_username'), 'ghostbusters', ['username'], unique=True)
    op.create_table('ghosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ghost_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('power_level', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('captured', 'not captured', name='ghost_status_enum'), nullable=True),
    sa.Column('special_abilities', sa.String(length=140), nullable=True),
    sa.Column('api_endpoint', sa.String(length=255), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('ghost_captured_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ghost_captured_by_user_id'], ['ghostbusters.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ghosts_ghost_name'), 'ghosts', ['ghost_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ghosts_ghost_name'), table_name='ghosts')
    op.drop_table('ghosts')
    op.drop_index(op.f('ix_ghostbusters_username'), table_name='ghostbusters')
    op.drop_index(op.f('ix_ghostbusters_email'), table_name='ghostbusters')
    op.drop_table('ghostbusters')
    # ### end Alembic commands ###
